package com.maogh.blog.core.model;

// Generated 2013-1-29 22:26:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

import com.maogh.app.model.GenericEntity;

/**
 * BlogAlbum generated by hbm2java
 */
@Entity
@Table(name = "blog_album")
public class Album extends GenericEntity {
	private String name;
	private int isVisible;
	private String description;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(int isVisible) {
		this.isVisible = isVisible;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
