package com.maogh.blog.core.model;

// Generated 2013-1-29 22:26:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.maogh.app.model.GenericEntity;

/**
 * BlogArticle generated by hbm2java
 */
@Entity
@Table(name = "blog_article")
public class Article extends GenericEntity {
	private String title;
	private String content;
	private long catalogId;
	private Long accessoryId;
	private String labels;
	private int isVisible;
	private Date modifyTime;

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public long getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(long catalogId) {
		this.catalogId = catalogId;
	}

	public Long getAccessoryId() {
		return this.accessoryId;
	}

	public void setAccessoryId(Long accessoryId) {
		this.accessoryId = accessoryId;
	}

	public String getLabels() {
		return this.labels;
	}

	public void setLabels(String labels) {
		this.labels = labels;
	}

	public int getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(int isVisible) {
		this.isVisible = isVisible;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
