package com.maogh.blog.core.model;

// Generated 2013-1-29 22:26:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.maogh.app.model.GenericEntity;

/**
 * BlogCatalog generated by hbm2java
 */
@Entity
@Table(name="blog_catalog")
public class Catalog extends GenericEntity {
	private String name;
	private Date modifyTime;
	private String description;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
