package com.maogh.blog.core.model;

// Generated 2013-1-29 22:26:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

import com.maogh.app.model.GenericEntity;

/**
 * BlogFile generated by hbm2java
 */
@Entity
@Table(name = "blog_file")
public class File extends GenericEntity {
	private String originalName;
	private String uniqueName;
	private String absolutePath;

	public String getOriginalName() {
		return this.originalName;
	}

	public void setOriginalName(String originalName) {
		this.originalName = originalName;
	}

	public String getUniqueName() {
		return this.uniqueName;
	}

	public void setUniqueName(String uniqueName) {
		this.uniqueName = uniqueName;
	}

	public String getAbsolutePath() {
		return this.absolutePath;
	}

	public void setAbsolutePath(String absolutePath) {
		this.absolutePath = absolutePath;
	}
}
