package com.maogh.blog.core.model;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.maogh.app.model.GenericEntity;

// Generated 2013-1-29 22:26:37 by Hibernate Tools 3.4.0.CR1

/**
 * BlogPhoto generated by hbm2java
 */
@Entity
@Table(name = "blog_photo")
public class Photo extends GenericEntity {
	private long albumId;
	private long fileId;
	private String description;

	public long getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(long albumId) {
		this.albumId = albumId;
	}

	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
