package com.maogh.blog.core.model;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.maogh.app.model.GenericEntity;

// Generated 2013-1-29 22:26:37 by Hibernate Tools 3.4.0.CR1

/**
 * BlogPhotoReply generated by hbm2java
 */
@Entity
@Table(name = "blog_photo_reply")
public class PhotoReply extends GenericEntity {
	private long replyId;
	private Long bloId;

	public long getReplyId() {
		return this.replyId;
	}

	public void setReplyId(long replyId) {
		this.replyId = replyId;
	}

	public Long getBloId() {
		return this.bloId;
	}

	public void setBloId(Long bloId) {
		this.bloId = bloId;
	}

}
