package com.maogh.blog.core.model;

// Generated 2013-1-29 22:26:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.Table;

import com.maogh.app.model.GenericEntity;

/**
 * BlogReply generated by hbm2java
 */
@Entity
@Table(name = "blog_reply")
public class Reply extends GenericEntity {
	private String name;
	private String email;
	private String comment;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
